// japanese
var translations={			
'Copy this text and keep it somewhere safe!'	:	'このテキストをコピーして、どこか安全なところへ保持してください!'	,
'Please paste in the text that was given to you on save export.'	:	'セーブをエクスポートした時のテキストを張り付けてください'	,
'Error while saving.<br>Export your save instead!'	:	'セーブ中のエラー。<br>代わりにセーブをエクスポートしてください!'	,
'Game saved'	:	'ゲームをセーブしました'	,
'Game loaded'	:	'ゲームをロードしました'	,
'Game reset'	:	'ゲームをリセットしました'	,
'You earn {0} heavenly chip{1}!'	:	'{0}の天のチップ{1}をもたらします!'	,
's'	:	''	,
'Frenzy : cookie production x7 for {0} seconds!'	:	'熱狂 : {0}秒間のクッキー生産x7!'	,
'Lucky! +{0} cookies!'	:	'幸運! +{0}クッキー!'	,
'Ruin! Lost {0} cookies!'	:	'破滅! {0}クッキーが失われた!'	,
'Elder frenzy : cookie production x666 for {0} seconds!'	:	'年上の熱狂 : {0}秒間 クッキー生産x666倍!'	,
'Clot : cookie production halved for {0} seconds!'	:	'固まり : {0}秒間 クッキー生産が半分に!'	,
'Click frenzy! Clicking power x777 for {0} seconds!'	:	'クリック熱狂! {0}秒間 クリック力がx777倍!'	,
'Cookie chain : +{0} cookies!'	:	'クッキー鎖 : +{0}クッキー!'	,
' days'	:	'日'	,
'1 day'	:	'1日'	,
' hours'	:	'時間'	,
'1 hour'	:	'1時間'	,
' minutes'	:	'分'	,
'1 minute'	:	'1分'	,
' seconds'	:	'秒'	,
'1 second'	:	'1秒'	,
'<div class="section">Menu</div>'	:	'<div class="section">メニュー</div>'	,
'<div class="title">General</div>'	:	'<div class="title">一般</div>'	,
'<div class="listing"><a class="option" onclick="Game.WriteSave();">Save</a><label>Save manually (the game autosaves every 60 seconds)</label></div>'	:	'<div class="listing"><a class="option" onclick="Game.WriteSave();">セーブ</a><label>手動セーブ(ゲームは60秒ごとに自動セーブします)</label></div>'	,
'<div class="listing"><a class="option" onclick="Game.ExportSave();">Export save</a><a class="option" onclick="Game.ImportSave();">Import save</a><label>You can use this to backup your save or to transfer it to another computer</label></div>'	:	'<div class="listing"><a class="option" onclick="Game.ExportSave();">セーブをエクスポート</a>・<a class="option" onclick="Game.ImportSave();">セーブをインポート</a><label>セーブのバックアップや別のコンピューターへの転送に使えます</label></div>'	,
'<div class="listing"><span class="warning" style="font-size:12px;">[Note : importing saves from earlier versions than 1.0 will be disabled beyond September 1st, 2013.]</span></div>'	:	'<div class="listing"><span class="warning" style="font-size : 12px;">[注 : 1.0より古いバージョンからセーブをインポートすることは2013年9月1日以降無効になります。]。</span></div>'	,
'<div class="listing"><a class="option warning" onclick="Game.Reset();">Reset</a><label>Reset your game (you will keep your achievements)</label></div>'	:	'<div class="listing"><a class="option warning" onclick="Game.Reset();">リセット</a><label>ゲームをリセットします(実績を維持します)。</label></div>'	,
'<div class="listing"><a class="option warning" onclick="Game.HardReset();">Wipe save</a><label>Delete all your progress, including your achievements and prestige</label></div>'	:	'<div class="listing"><a class="option warning" onclick="Game.HardReset();">セーブを削除</a><label>実績と名声を含むすべての進行を削除します。</label></div>'	,
'<div class="title">Settings</div>'	:	'<div class="title">設定</div>'	,
'<div class="listing">'	:	'<div class="listing">'	,
'Fancy graphics ON'	:	'装飾グラフィックスON'	,
'Fancy graphics OFF'	:	'装飾グラフィックスOFF'	,
'Particles ON'	:	'粒子ON'	,
'Particles OFF'	:	'粒子OFF'	,
'Numbers ON'	:	'数字ON'	,
'Numbers OFF'	:	'数字OFF'	,
'Milk ON'	:	'ミルクON'	,
'Milk OFF'	:	'ミルクOFF'	,
'Offline mode OFF'	:	'オフライン・モードOFF'	,
'Offline mode ON'	:	'オフライン・モードON'	,
'<label>(note : this disables update notifications)</label></div>'	:	'<label>(注 : これは更新通知を無効にします)</label></div>'	,
'Autosave ON'	:	'自動セーブON'	,
'Autosave OFF'	:	'自動セーブOFF'	,
'[Upgrade]'	:	'[アップグレード]'	,
' [Purchased]'	:	' [購入済]'	,
'[Achievement]'	:	'[実績]'	,
' [Unlocked]'	:	' [アンロック]'	,
'plain milk'	:	'普通のミルク'	,
'raspberry milk'	: 	'ラズベリー・ミルク'	,
'chocolate milk'	:	'チョコレート・ミルク'	,
'<div class="section">Statistics</div>'	:	'<div class="section">統計</div>'	,
'awoken'	:	'awoken'	, 
'displeased'	:	'不快にされました'	, 
'angered'	:	'怒りました'	, 
'appeased'	:	'和らげられました'	, 
'<div class="listing"><b>Cookies in bank :</b> <div class="price plain">'	:	'<div class="listing"><b>銀行のクッキー : </b><div class="price plain">'	,
'<div class="listing"><b>Cookies baked (all time) :</b> <div class="price plain">'	:	'<div class="listing"><b>焼いたクッキー(すべての時間) : </b><div class="price plain">'	,
'<div class="listing"><b>Cookies forfeited by resetting :</b> <div class="price plain">'	:	'<div class="listing"><b>リセットにより没収されたクッキー : </b><div class="price plain">'	,
'<div class="listing"><b>Game started :</b> '	:	'<div class="listing"><b>ゲーム開始 :</b>'	,
' ago</div>'	:	'前</div>'	,
'<div class="listing"><b>Buildings owned :</b> '	:	'<div class="listing"><b>所有する建物 :</b>'	,
'<div class="listing"><b>Cookies per second :</b> '	:	'<div class="listing"><b>毎秒クッキー :</b>'	,
' <small>(multiplier : '	:	'<small>(乗数 : )'	,
'%)</small></div>'	:	'%)</small></div>'	,
'<div class="listing"><b>Cookies per click :</b> '	:	'<div class="listing"><b>1クリック当たりのクッキー :</b>'	,
'<div class="listing"><b>Cookie clicks :</b> '	:	'<div class="listing"><b>クッキーはクリックします :</b>'	,
'<div class="listing"><b>Hand-made cookies :</b> '	:	'<div class="listing"><b>手製のクッキー :</b>'	,
'<div class="listing"><b>Golden cookie clicks :</b> '	:	'<div class="listing"><b>金のクッキーはクリックします :</b>'	,
' <span class="hidden">(<b>Missed golden cookies :</b> '	:	'<span class="hidden">(<b>抜かされた金のクッキー</b> : )'	,
')</span></div>'	:	')</span></div>'	,
'<br><div class="listing"><b>Running version :</b> '	:	'<br><div class="listing"><b>実行中のバージョン :</b>'	,
'<div class="listing"><b>Research :</b> '	:	'<div class="listing"><b>研究 :</b>'	,
' remaining</div>'	:	'残り</div>'	,
'<div class="listing"><b>Grandmatriarchs status :</b> '	:	'<div class="listing"><b>おばあちゃんtriarchsステータス :</b>'	,
'<div class="listing"><b>Pledge :</b> '	:	'<div class="listing"><b>誓約 :</b>'	,
'<div class="title">Prestige</div>'	:	'<div class="title">名声</div>'	,
'<div class="listing"><small>(Note : each heavenly chip grants you +2% CpS multiplier. You can gain more chips by resetting with a lot of cookies.)</small></div>'	:	'<div class="listing"><small>(注 : 天のチップはそれぞれあなたに+2%のCpSをより複合的に与えます。多くのクッキーでリセットすることによりより多くのチップを獲得することができます。)</small></div>'	,
'<div class="title">Upgrades unlocked</div>'	:	'<div class="title">アップグレードがアンロックされました。</div>'	,
'<div class="listing"><b>Unlocked :</b> '	:	'<div class="listing"><b>アンロックされました :</b>'	,
'<div class="title">Achievements</div>'	:	'<div class="title">実績</div>'	,
'<div class="listing"><b>Milk :</b> '	:	'<div class="listing"><b>ミルク :</b>'	,
') <small>(Note : you gain milk through achievements. Milk can unlock unique upgrades over time.)</small></div>'	:	'(<small>注 : 実績によってミルクを獲得します。ミルクはユニークなアップグレードを時間にわたって開けることができます</small>。)</div>'	,
'<div class="listing"><b>Shadow achievements</b> <small>(These are feats that are either unfair or difficult to attain. They do not give milk.)</small></div>'	:	'<div class="listing"><b>影実績</b>(<small>これらは、不公平か、到達するのが難しい功績です。それらはミルクを与えません</small>。)</div>'	,
'<q>Moist cookies.</q><sig>grandma</sig>'	:	'<q>湿ったクッキー。</q><sig>おばあちゃん</sig>'	,
'<q>We\'re nice grandmas.</q><sig>grandma</sig>'	:	'<q>私たちはよいおばあちゃんです。</q><sig>おばあちゃん</sig>'	,
'<q>Indentured servitude.</q><sig>grandma</sig>'	:	'<q>年季奉公の奴隷状態。</q><sig>おばあちゃん</sig>'	,
'<q>Come give grandma a kiss.</q><sig>grandma</sig>'	:	'<q>来る、おばあちゃんにキスを与えます。</q><sig>おばあちゃん</sig>'	,
'<q>Why don\'t you visit more often?</q><sig>grandma</sig>'	:	'<q>よりしばしば訪れてはどうですか。</q><sig>おばあちゃん</sig>'	,
'<q>Call me...</q><sig>grandma</sig>'	:	'<q>私に電話してください...</q><sig>おばあちゃん</sig>'	,
'<q>Absolutely disgusting.</q><sig>grandma</sig>'	:	'<q>絶対にうんざりさせること。</q><sig>おばあちゃん</sig>'	,
'<q>You make me sick.</q><sig>grandma</sig>'	:	'<q>あなたは私の気分を悪くします。</q><sig>おばあちゃん</sig>'	,
'<q>You disgust me.</q><sig>grandma</sig>'	:	'<q>あなたは私をうんざりさせます。</q><sig>おばあちゃん</sig>'	,
'<q>We rise.</q><sig>grandma</sig>'	:	'<q>私たちは起きます。</q><sig>おばあちゃん</sig>'	,
'<q>It begins.</q><sig>grandma</sig>'	:	'<q>それは始まります。</q><sig>おばあちゃん</sig>'	,
'<q>It\'ll all be over soon.</q><sig>grandma</sig>'	:	'<q>それはすべてまもなく終わるでしょう。</q><sig>おばあちゃん</sig>'	,
'<q>You could have stopped it.</q><sig>grandma</sig>'	:	'<q>それを止めることができました。</q><sig>おばあちゃん</sig>'	,
'News : cookie manufacturer downsizes, sells own grandmother!'	:	'ニュース : クッキー・メーカーは小型化します、自分の祖母に売る!'	,
'<q>It has betrayed us, the filthy little thing.</q><sig>grandma</sig>'	:	'<q>それは私たち、不潔な小さなものを裏切りました。</q><sig>おばあちゃん</sig>'	,
'<q>It tried to get rid of us, the nasty little thing.</q><sig>grandma</sig>'	:	'<q>それは、私たち、不快な小さなものを追い払おうとしました。</q><sig>おばあちゃん</sig>'	,
'<q>It thought we would go away by selling us. How quaint.</q><sig>grandma</sig>'	:	'<q>それは、私たちに売ることにより、私たちは去るだろうと思いました。どれくらい奇妙か。</q><sig>おばあちゃん</sig>'	,
'<q>I can smell your rotten cookies.</q><sig>grandma</sig>'	:	'<q>私は腐敗しているクッキーの臭いをかぐことができます。</q><sig>おばあちゃん</sig>'	,
'<q>shrivel</q><sig>grandma</sig>'	:	'<q>しなびます。</q><sig>おばあちゃん</sig>'	,
'<q>writhe</q><sig>grandma</sig>'	:	'<q>苦悶</q><sig>おばあちゃん</sig>'	,
'<q>throb</q><sig>grandma</sig>'	:	'<q>振動</q><sig>おばあちゃん</sig>'	,
'<q>gnaw</q><sig>grandma</sig>'	:	'<q>腐食します。</q><sig>おばあちゃん</sig>'	,
'<q>We will rise again.</q><sig>grandma</sig>'	:	'<q>私たちは再び起きるでしょう。</q><sig>おばあちゃん</sig>'	,
'<q>A mere setback.</q><sig>grandma</sig>'	:	'<q>単なる後退。</q><sig>おばあちゃん</sig>'	,
'<q>We are not satiated.</q><sig>grandma</sig>'	:	'<q>私たちは飽き飽きしません。</q><sig>おばあちゃん</sig>'	,
'<q>Too late.</q><sig>grandma</sig>'	:	'<q>遅すぎます。</q><sig>おばあちゃん</sig>'	,
'News : cookie farms suspected of employing undeclared elderly workforce!'	:	'ニュース : 無申告の初老の労働力を使用した疑いをかけられたクッキー農場!'	,
'News : cookie farms release harmful chocolate in our rivers, says scientist!'	:	'ニュース : クッキー農場は、私たちの川、発言権科学者の有害なチョコレートをリリースします!'	,
'News : genetically-modified chocolate controversy strikes cookie farmers!'	:	'ニュース : 遺伝子組み換えのチョコレート論争はクッキー農民を打ちます!'	,
'News : free-range farm cookies popular with today\'s hip youth, says specialist.'	:	'ニュース : 今日の粋な若さに人気のある放し飼いにした農場クッキー、専門家は言います。'	,
'News : farm cookies deemed unfit for vegans, says nutritionist.'	:	'ニュース : 農場クッキーは認めました、完全菜食主義者に適さない、栄養学者は言います。'	,
'News : cookie factories linked to global warming!'	:	'ニュース : 地球温暖化にリンクされたクッキー工場!'	,
'News : cookie factories involved in chocolate weather controversy!'	:	'ニュース : チョコレート天候論争に含まれるクッキー工場!'	,
'News : cookie factories on strike, robotic minions employed to replace workforce!'	:	'ニュース : ストライキ中のクッキー工場、労働力を交換するために雇用されたロボット工学的な手先!'	,
'News : cookie factories on strike - workers demand to stop being paid in cookies!'	:	'ニュース : ストライキ中のクッキー工場 - 労働者は、クッキーの中で払われることをやめることを要求します!'	,
'News : factory-made cookies linked to obesity, says study.'	:	'ニュース : 工場に作られたクッキーは、肥満にリンクした、と研究が言います。'	,
'News : {0} miners dead in chocolate mine catastrophe!'	:	'ニュース : チョコレート鉱山大災害において死んだ{0}鉱夫!'	,
'News : {0} miners trapped in collapsed chocolate mine!'	:	'ニュース : 崩壊したチョコレート鉱山の中に閉じ込められた{0}鉱夫!'	,
'News : chocolate mines found to cause earthquakes and sink holes!'	:	'ニュース : 地震を引き起こし、穴を沈める、と分かったチョコレート鉱山!'	,
'News : chocolate mine goes awry, floods village in chocolate!'	:	'ニュース : チョコレート鉱山は失敗に終ります、チョコレート中の洪水村!'	,
'News : depths of chocolate mines found to house "peculiar, chocolaty beings"!'	:	'ニュース : 「特有のチョコレートのようなもの」を収容すると分かったチョコレート鉱山の真中!'	,
'News : new chocolate planet found, becomes target of cookie-trading spaceships!'	:	'ニュース : 新しいチョコレート惑星は見つけました、クッキーを取り引きする宇宙船の目標になる!'	,
'News : massive chocolate planet found with 99.8% certified pure dark chocolate core!'	:	'ニュース : 99.8%で見つかった巨大なチョコレート惑星は純粋なダーク・チョコレート芯を証明しました!'	,
'News : space tourism booming as distant planets attract more bored millionaires!'	:	'ニュース : 離れた惑星がより多くの退屈した百万長者を引きつけるとともに急激に景気づく宇宙旅行!'	,
'News : chocolate-based organisms found on distant planet!'	:	'ニュース : 離れた惑星で見つけられたチョコレートベースの有機体!'	,
'News : ancient baking artifacts found on distant planet; "terrifying implications", experts say.'	:	'ニュース : 離れた惑星で見つけられた、古代の焼けるアーティファクト;「恐ろしい含意」とエキスパートは言います。'	,
'News : national gold reserves dwindle as more and more of the precious mineral is turned to cookies!'	:	'ニュース : ますます貴重な鉱物でのように、全国正貨準備は減少します、クッキーに向けられる!'	,
'News : chocolate jewelry found fashionable, gold and diamonds "just a fad", says specialist.'	:	'ニュース : チョコレート宝石は流行で、見つけました、金とダイヤモンドの「単なる熱」は専門家と言います。'	,
'News : silver found to also be transmutable into white chocolate!'	:	'ニュース : 銀はさらにホワイトチョコレートへ変化可能なために見つけました!'	,
'News : defective alchemy lab shut down, found to convert cookies to useless gold.'	:	'ニュース : 不完全な錬金術研究所はシャット・ダウンしました、クッキーを役立たない金に変換するために見つけました。'	,
'News : alchemy-made cookies shunned by purists!'	:	'ニュース : 純正主義者で回避された、錬金術に作られたクッキー!'	,
'News : nation worried as more and more unsettling creatures emerge from dimensional portals!'	:	'ニュース : ますます動揺する創造物が次元のポータルから出現するとともに、国家は心配しました!'	,
'News : dimensional portals involved in city-engulfing disaster!'	:	'ニュース : 都市を飲み込む災害に含まれる次元のポータル!'	,
'News : tourism to cookieverse popular with bored teenagers! Casualty rate as high as 73%!'	:	'ニュース : 退屈したティーンエイジャーに人気のあるクッキー宇宙への観光旅行!死傷者割合は73%高い!'	,
'News : cookieverse portals suspected to cause fast aging and obsession with baking, says study.'	:	'ニュース : クッキー宇宙ポータルは速く老化することとから焼きへの執念を引き起こすために疑った、と研究が言います。'	,
'News : "do not settle near portals," says specialist; "your children will become strange and corrupted inside."'	:	'ニュース : 「ポータルの近くで解決しないでください」と専門家は言います;「子どもたちは、内側に奇妙で、悪くなったようになるでしょう。」'	,
'News : time machines involved in history-rewriting scandal! Or are they?'	:	'ニュース : 歴史を書き直すスキャンダルに含まれるタイムマシン!あるいは、それらはです?'	,
'News : time machines used in unlawful time tourism!'	:	'ニュース : 不法の時間観光旅行の中で使用されるタイムマシン!'	,
'News : cookies brought back from the past "unfit for human consumption", says historian.'	:	'ニュース : クッキーは戻しました、から、過去「人間の消費に適さない」、歴史家は言います。'	,
'News : various historical figures inexplicably replaced with talking lumps of dough!'	:	'ニュース : 生地の話す塊と不可解に取り替えられた様々な歴史上の図!'	,
'News : "I have seen the future," says time machine operator, "and I do not wish to go there again."'	:	'ニュース : 「私は将来を見ました」とタイムマシン・オペレーターが言います。「また、私は再びそこに行きたくない」'	,
'News : whole town seemingly swallowed by antimatter-induced black hole; more reliable sources affirm town "never really existed"!'	:	'ニュース : 反物質に引き起こされたブラックホールで外見は呑み込まれた町全体;もっと信頼できる出所は町を支持します「実際に存在しなかった!」'	,
'News : "explain to me again why we need particle accelerators to bake cookies?" asks misguided local woman.'	:	'ニュース : 「なぜクッキーを焼くために私たちが粒子加速器を必要とするか再び私に説明しますか。」見当違いの地方の女性は尋ねます。'	,
'News : first antimatter condenser successfully turned on, doesn\'t rip apart reality!'	:	'ニュース : 成功裡につけられた第1の反物質コンデンサーは現実を引き裂きません!'	,
'News : researchers conclude that what the cookie industry needs, first and foremost, is "more magnets".'	:	'ニュース : 研究者は、クッキー産業が第一に必要とするものが「より多くの磁石」であると結論を下します。'	,
'News : "unravelling the fabric of reality just makes these cookies so much tastier", claims scientist.'	:	'ニュース : 「現実の構造を解くことはこれらのクッキーをちょうど非常にはるかに味がよくします」と科学者が主張します。'	,
'News : cookie manufacturer completely forgoes common sense, lets OCD drive building decisions!'	:	'ニュース : クッキー・メーカーは完全に常識(決定を構築する貸家OCDドライブ)を断念します!'	,
'News : follow the tear-jerking, riches-to-rags story about a local cookie manufacturer who decided to give it all up!'	:	'ニュース : お涙頂戴のものに続く、それにすべてを与えることを決定した地方のクッキー・メーカーの富からぼろへの話!'	,
'News : known universe now jammed with cookies! No vacancies!'	:	'ニュース : 今、クッキーでいっぱいになった既知の宇宙!空位はありません。'	,
'News : local cookie manufacturer becomes luckiest being alive!'	:	'ニュース : 地方のクッキー・メーカーは生きていて、最も幸運になります!'	,
'News : faint meowing heard around local cookie facilities; suggests new ingredient being tested.'	:	'ニュース : にゃーおと鳴いている気絶は、ローカルのクッキー設備のまわりで聞きました;テストされている新しい成分を示唆します。'	,
'News : crowds of meowing kittens with little hard hats reported near local cookie facilities.'	:	'ニュース : 小さな安全帽を備えたにゃーおと鳴く子ネコの群衆はローカルのクッキー設備の近くで報告しました。'	,
'News : surroundings of local cookie facilities now overrun with kittens in adorable little suits. Authorities advise to stay away from the premises.'	:	'ニュース : 今、愛らしい小さなスーツでの子ネコがはびこっていたローカルのクッキー設備の環境。当局は家屋敷を避けるために助言します。'	,
'News : locals report troups of bossy kittens meowing adorable orders at passerbys.'	:	'ニュース : 地元住民は親分風を吹かす子ネコのtroupsがにゃーおと鳴くことを報告します、passerbysの愛らしい注文。'	,
'newts'	:	'イモリ'	,
'penguins'	:	'ペンギン'	,
'scorpions'	:	'サソリ'	,
'axolotls'	:	'アホロートル'	,
'puffins'	:	'ツノメドリ'	,
'porpoises'	:	'イルカ'	,
'blowfish'	:	'フグ'	,
'horses'	:	'馬'	,
'crayfish'	:	'ザリガニ'	,
'slugs'	:	'ナメクジ'	,
'humpback whales'	:	'ザトウクジラ'	,
'nurse sharks'	:	'テンジクザメ'	,
'giant squids'	:	'オオイカ'	,
'polar bears'	:	'北極グマ'	,
'fruit bats'	:	'フルーツコウモリ'	,
'frogs'	:	'てっさ'	,
'sea squirts'	:	'ホヤ'	,
'velvet worms'	:	'カギムシ'	,
'mole rats'	:	'メクラネズミ'	,
'paramecia'	:	'ゾウリムシ'	,
'nematodes'	:	'線虫'	,
'tardigrades'	:	'緩歩類'	,
'giraffes'	:	'キリン'	,
'News : '	:	'ニュース : '	,
'cookies found to {0} in {1}!'	:	'クッキーは{0}に{1}に見つけました!'	,
'increase lifespan'	:	'増加寿命'	,
'sensibly increase intelligence'	:	'賢明に増加知能'	,
'reverse aging'	:	'逆老化'	,
'decrease hair loss'	:	'減少脱毛'	,
'prevent arthritis'	:	'関節炎を防ぎます。'	,
'cure blindness'	:	'治療無分別'	,
'cookies found to make {0} {1}!'	:	'{0}{1}を作ると分かったクッキー!'	,
'more docile'	:	'さらに多く、従順'	,
'more handsome'	:	'さらに多く、ハンサム'	,
'nicer'	:	'よりよい。'	,
'less hungry'	:	'それほど空腹でありません。'	,
'more pragmatic'	:	'より実用的'	,
'tastier'	:	'より味がよい。'	,
'cookies tested on {0}, found to have no ill effects.'	:	'{0}の上でテストされたクッキー、悪い効果がないために見つけました。'	,
'cookies unexpectedly popular among {0}!'	:	'{0}に不意に人気のあるクッキー!'	,
'unsightly lumps found on {0} near cookie facility; "they\'ve pretty much always looked like that", say biologists.'	:	'クッキー設備の近くで{0}の上で見つかった見苦しい塊;「彼らはそのように常に見えました」と生物学者が言います。'	,
'new species of {0} discovered in distant country; "yup, tastes like cookies", says biologist.'	:	'離れた国で発見された{0}の新種;「はい、味はクッキーが好きです」と生物学者が言います。'	,
'cookies go well with roasted {0}, says controversial chef.'	:	'クッキーは、焼かれた{0}とうまく行く、と論争好きなシェフが言います。'	,
'"do your cookies contain {0}?", asks PSA warning against counterfeit cookies.'	:	'「クッキーは{0}を含みますか。」と偽造のクッキーに対するPSAの警告が尋ねます。'	,
'News : "{0}", reveals celebrity.'	:	'ニュース : 「{0}」、名声を明らかにします。'	,
'I\'m all about cookies'	:	'私は、クッキーにすべて関係しています。'	,
'I just can\'t stop eating cookies. I think I seriously need help'	:	'私はクッキーを食べることをまったくやめることができません。私は、真面目に支援する必要があると思います。'	,
'I guess I have a cookie problem'	:	'私は、クッキー問題を持っていると推測します。'	,
'I\'m not addicted to cookies. That\'s just speculation by fans with too much free time'	:	'私はクッキーに中毒ではありません。それはあまりにも多くの自由時間のファンによる単に推測です。'	,
'my upcoming album contains 3 songs about cookies'	:	'私の来たるアルバムは、クッキーに関する3曲の歌を含んでいます。'	,
'I\'ve had dreams about cookies 3 nights in a row now. I\'m a bit worried honestly'	:	'私は、今、列の中でクッキー3夜に関する夢を見ました。私は少し正直に心配します。'	,
'accusations of cookie abuse are only vile slander'	:	'クッキー乱用の告発は単なる下劣な中傷です。'	,
'cookies really helped me when I was feeling low'	:	'私が低く感じていた時、クッキーは実際に私を助けました。'	,
'cookies are the secret behind my perfect skin'	:	'クッキーは私の完全な皮膚の後ろの秘密です。'	,
'cookies helped me stay sane while filming my upcoming movie'	:	'クッキーは、私が私の来たる映画を製作する間に健全に続けるのを助けました。'	,
'cookies helped me stay thin and healthy'	:	'クッキーは、私が薄く、健康に続けるのを助けました。'	,
'I\'ll say one word, just one : cookies'	:	'私は1単語、ちょうど1を言いましょう : クッキー'	,
'alright, I\'ll say it - I\'ve never eaten a single cookie in my life'	:	'確かに、私はそれを言いましょう。私は人生で単一のクッキーを食べたことがありません。'	,
'doctors recommend twice-daily consumption of fresh cookies.'	:	'ドクターは、新鮮なクッキーの二倍一日当りの消費を推奨します。'	,
'doctors warn against chocolate chip-snorting teen fad.'	:	'ドクターはチョコレートチップを鼻を鳴らすティーンエージャーの一時の流行に対して警告します。'	,
'doctors advise against new cookie-free fad diet.'	:	'ドクターは新しいクッキーなしのファッド・ダイエットに対して助言します。'	,
'doctors warn mothers about the dangers of "home-made cookies".'	:	'ドクターは「手製のクッキー」の危険に関して母親を警告します。'	,
'News : scientist predicts imminent cookie-related "end of the world"; becomes joke among peers.'	:	'ニュース : 科学者は切迫したクッキー関連の「世界の終わり」を予言します;仲間の間の冗談になります。'	,
'News : man robs bank, buys cookies.'	:	'ニュース : 人は銀行、買いクッキーで強盗をします。'	,
'News : what makes cookies taste so right? "Probably all the [*****] they put in them", says anonymous tipper.'	:	'ニュース : 何がクッキーに非常に正しい味がさせますか。「恐らくそれらがそれらに入れる[*****]すべてと匿名のチップを与える人はと言います。'	,
'News : man found allergic to cookies; "what a weirdo", says family.'	:	'ニュース : 人は見つけました、クッキーに対してアレルギー;「何、変人。」家族は言います。'	,
'News : foreign politician involved in cookie-smuggling scandal.'	:	'ニュース : クッキーを密輸するスキャンダルに関与する外部政治家。'	,
'News : cookies now more popular than {0}, says study.'	:	'ニュース : {0}よりポピュラーなクッキー今は研究を言います。'	,
'cough drops'	:	'咳止めドロップ'	,
'broccoli'	:	'ブロッコリ'	,
'smoked herring'	:	'薫製のニシン'	,
'cheese'	:	'チーズ'	,
'video games'	:	'ビデオゲーム'	,
'stable jobs'	:	'安定したジョブ'	,
'relationships'	:	'関係'	,
'time travel'	:	'タイムトラベル'	,
'cat videos'	:	'猫ビデオ'	,
'tango'	:	'タンゴ'	,
'fashion'	:	'流行'	,
'television'	:	'テレビ'	,
'nuclear warfare'	:	'核戦争'	,
'whatever it is we ate before'	:	'それが何でも、私たちは以前に食べました。'	,
'politics'	:	'政治'	,
'oxygen'	:	'酸素'	,
'lamps'	:	'ランプ'	,
'News : obesity epidemic strikes nation; experts blame {0}.'	:	'ニュース : 肥満流行病は国家を打ちます;エキスパートは{0}を非難します。'	,
'twerking'	:	'twerking'	,
'that darn rap music'	:	'その繕いラップミュージック'	,
'video-games'	:	'ビデオゲーム'	,
'lack of cookies'	:	'クッキーの不足'	,
'mysterious ghostly entities'	:	'不可解な幽霊の実体'	,
'aliens'	:	'外国人'	,
'parents'	:	'親'	,
'schools'	:	'学校'	,
'comic-books'	:	'コミック'	,
'cookie-snorting fad'	:	'クッキーを鼻を鳴らす一時の流行'	,
'News : cookie shortage strikes town, people forced to eat cupcakes; "just not the same", concedes mayor.'	:	'ニュース : クッキー不足は町(カップケーキを食べることを強いられた人々)を打ちます;「ない(ちょうど)同じ。」市長を与えます。'	,
'News : "you gotta admit, all this cookie stuff is a bit ominous", says confused idiot.'	:	'ニュース : 「あなたは認めなければなりません。このクッキー材料はすべて少し不吉です」と混乱した白痴が言います。'	,
'News : movie cancelled from lack of actors; "everybody\'s at home eating cookies", laments director.'	:	'ニュース : 俳優の不足から取り消された映画;「クッキーを食べるホームで皆の。。」の、悲嘆監督。'	,
'News : comedian forced to cancel cookie routine due to unrelated indigestion.'	:	'ニュース : コメディアンは無関係な消化不良によりクッキー・ルーチンを取り消すために強要しました。'	,
'News : new cookie-based religion sweeps the nation.'	:	'ニュース : 新しいクッキーベースの宗教は国家を掃きます。'	,
'News : fossil records show cookie-based organisms prevalent during Cambrian explosion, scientists say.'	:	'ニュース : 化石記録はカンブリア爆発中に普及しているクッキーベースの有機体を示す、と科学者が言います。'	,
'News : mysterious illegal cookies seized; "tastes terrible", says police.'	:	'ニュース : 不可解なイリーガルのクッキーはとらえました;「恐ろしい味がする」と警察は言います。'	,
'News : man found dead after ingesting cookie; investigators favor "mafia snitch" hypothesis.'	:	'ニュース : クッキーを受容した後に死んでいるのが見つかった人;調査者は「マフィア密告者」仮説に賛成します。'	,
'News : "the universe pretty much loops on itself," suggests researcher; "it\'s cookies all the way down."'	:	'ニュース : 「宇宙は、ほとんどそれ自体の上でループします」と研究者が示唆します;「それは途中ずっと下へクッキーです。」'	,
'News : minor cookie-related incident turns whole town to ashes; neighboring cities asked to chip in for reconstruction.'	:	'ニュース : 小さなクッキー関連の出来事は町全体を灰に向けます;近隣の都市は、再構成のために口出しさせてくれるように頼みました。'	,
'News : is our media controlled by the cookie industry? This could very well be the case, says crackpot conspiracy theorist.'	:	'ニュース : 私たちのメディアはクッキー産業でコントロールされますか。これは非常によくそうかもしれない、と変な共謀理論家が言います。'	,
'cookie-flavored popcorn pretty damn popular; "we kinda expected that", say scientists.'	:	'クッキーに風味をつけたきれいなポップコーン、ポピュラーで非難する;「私たちはまあそれを期待しました」と科学者が言います。'	,
'cookie-flavored cereals break all known cereal-related records'	:	'クッキー味のシリアルは既知のシリアル関連の記録をすべて破ります。'	,
'cookies popular among all age groups, including fetuses, says study.'	:	'胎児、発言権研究をインクルードするすべての年齢集団に人気のあるクッキー。'	,
'cookie-flavored popcorn sales exploded during screening of Grandmothers II : The Moistening.'	:	'クッキーに風味をつけたポップコーン販売は、祖母IIの検査中に爆発しました : 湿ること。'	,
'News : all-cookie restaurant opening downtown. Dishes such as braised cookies, cookie thermidor, and for dessert : crepes.'	:	'ニュース : 全クッキー・レストランを開くダウンタウン。蒸し煮にされたクッキーのような皿、クッキーthermidor、そしてデザートのために : クレープ。'	,
'News : cookies could be the key to {0}, say scientists.'	:	'ニュース : クッキーは{0}の鍵かもしれない、と科学者が言います。'	,
'eternal life'	:	'永遠の生命'	,
'infinite riches'	:	'無限の富'	,
'eternal youth'	:	'永遠の若さ'	,
'eternal beauty'	:	'永遠の美'	,
'curing baldness'	:	'ハゲ治療'	,
'world peace'	:	'世界平和'	,
'solving world hunger'	:	'世界飢えの解決'	,
'ending all wars world-wide'	:	'世界的な戦争をすべて終結させること'	,
'making contact with extraterrestrial life'	:	'地球外生物と接触すること'	,
'mind-reading'	:	'読心術'	,
'better living'	:	'生活改善'	,
'better eating'	:	'よりよく食べること。'	,
'more interesting TV shows'	:	'より面白いテレビ番組'	,
'faster-than-light travel'	:	'超光速旅行'	,
'quantum baking'	:	'量子焼き'	,
'chocolaty goodness'	:	'チョコレートのような長所'	,
'gooder thoughtness'	:	'よりよいthoughtness'	,
'You feel like making cookies. But nobody wants to eat your cookies.'	:	'あなたはクッキーを作りたい。しかし、誰もクッキーを食べたくありません。'	,
'Your first batch goes to the trash. The neighborhood raccoon barely touches it.'	:	'最初のバッチはごみに行きます。近隣アライグマはかろうじてそれに触れます。'	,
'Your family accepts to try some of your cookies.'	:	'家族はクッキーのうちのいくつかを試みるために受理します。'	,
'Your cookies are popular in the neighborhood.'	:	'クッキーは近隣においてポピュラーです。'	,
'People are starting to talk about your cookies.'	:	'人々はクッキーについて話し始めています。'	,
'Your cookies are talked about for miles around.'	:	'クッキーは、マイルまわりに話されます。'	,
'Your cookies are renowned in the whole town!'	:	'クッキーは町全体において有名です!'	,
'Your cookies bring all the boys to the yard.'	:	'クッキーは少年をすべて庭へ連れて来ます。'	,
'Your cookies now have their own website!'	:	'今クッキーには自分のウェブサイトがあります!'	,
'Your cookies are worth a lot of money.'	:	'クッキーは、金銭に価値が非常にあります。'	,
'Your cookies sell very well in distant countries.'	:	'クッキーは、離れた国々で非常によく売ります。'	,
'People come from very far away to get a taste of your cookies.'	:	'人々は来ます、から、クッキーの味を得るために非常にずっと遠くに。'	,
'Kings and queens from all over the world are enjoying your cookies.'	:	'王と女王は世界中からクッキーを楽しんでいます。'	,
'There are now museums dedicated to your cookies.'	:	'今クッキーに専用博物館があります。'	,
'A national day has been created in honor of your cookies.'	:	'ナショナルデーは、クッキーに敬意を表して作成されました。'	,
'Your cookies have been named a part of the world wonders.'	:	'クッキーは世界驚異の一部と命名されました。'	,
'History books now include a whole chapter about your cookies.'	:	'歴史本は、今クッキーに関する全体の章を含んでいます。'	,
'Your cookies have been placed under government surveillance.'	:	'クッキーは政府監視下に置かれました。'	,
'The whole planet is enjoying your cookies!'	:	'惑星全体はクッキーを楽しんでいます!'	,
'Strange creatures from neighboring planets wish to try your cookies.'	:	'近隣の惑星からの奇妙な創造物はクッキーを試みたい。'	,
'Elder gods from the whole cosmos have awoken to taste your cookies.'	:	'宇宙全体からの年上の神は、クッキーを味わうためにawokenを持っていますように。'	,
'Beings from other dimensions lapse into existence just to get a taste of your cookies.'	:	'単にクッキーの味を得るために、他の次元からの生き物は存在に陥ります。'	,
'Your cookies have achieved sentience.'	:	'クッキーは感覚性を達成しました。'	,
'The universe has now turned into cookie dough, to the molecular level.'	:	'宇宙は分子レベルに、クッキー生地へ今変わりました。'	,
'Your cookies are rewriting the fundamental laws of the universe.'	:	'クッキーは、宇宙の基本法を書き直しています。'	,
'A local news station runs a 10-minute segment about your cookies. Success!<br><span style="font-size:50%;">(you win a cookie)</span>'	:	'ローカル・ニュース・ステーションは、クッキーに関する10分のセグメントを実行します。成功!<br><span style="font-size : 50%;">(クッキーを勝ち取ります。)</span>'	,
'it\'s time to stop playing'	:	'演じることをやめる時間です。'	,
'News : millions of old ladies reported missing!'	:	'ニュース : 何百万もの老婦人が見当たらずに報告しました!'	,
'News : processions of old ladies sighted around cookie facilities!'	:	'ニュース : クッキー設備のまわりで目撃された老婦人の行列!'	,
'News : families around the continent report agitated, transfixed grandmothers!'	:	'ニュース : 大陸のまわりの家族は動揺し突き通された祖母に報告します!'	,
'News : doctors swarmed by cases of old women with glassy eyes and a foamy mouth!'	:	'ニュース : ガラス質の目と泡状の口を持った年を取った女性の場合で押し寄せられたドクター!'	,
'News : nurses report "strange scent of cookie dough" around female elderly patients!'	:	'ニュース : 看護師は、女性の高齢の患者のまわりの「クッキー生地の奇妙な匂い」を報告します!'	,
'News : town in disarray as strange old ladies break into homes to abduct infants and baking utensils!'	:	'ニュース : 奇妙な老婦人が幼児を誘拐するために家に侵入するとともに無秩序中の町と焼ける器具!'	,
'News : sightings of old ladies with glowing eyes terrify local population!'	:	'ニュース : 強烈な目を持った老婦人の観測は地元住民を恐れさせます!'	,
'News : retirement homes report "female residents slowly congealing in their seats"!'	:	'ニュース : 退職者向けホームは、「彼らの座席でゆっくり凍結する女性の居住者」に報告します!'	,
'News : whole continent undergoing mass exodus of old ladies!'	:	'ニュース : 老婦人の多量流出を経験する全体の大陸!'	,
'News : old women freeze in place in streets, ooze warm sugary syrup!'	:	'ニュース : 年を取った女性は、通りで適所に立ちすくみます、暖かい砂糖のようなシロップを分泌する!'	,
'News : large "flesh highways" scar continent, stretch between various cookie facilities!'	:	'ニュース : 大きな「肉ハイウェイ」傷跡大陸(様々なクッキー設備間の伸張)!'	,
'News : wrinkled "flesh tendrils" visible from space!'	:	'ニュース : スペースから可視のしわが寄った「肉つる!」!'	,
'News : remains of "old ladies" found frozen in the middle of growing fleshy structures!'	:	'ニュース : 肉の構造を育てている最中に冷凍であるのが見つかった「老婦人」の遺体!'	,
'News : all hope lost as writhing mass of flesh and dough engulfs whole city!'	:	'ニュース : 肉と生地の多量の苦悶が都市全体を飲み込むとともに失われたすべての希望!'	,
'News : nightmare continues as wrinkled acres of flesh expand at alarming speeds!'	:	'ニュース : 肉のしわが寄った地所が速度に警報を発することで拡大するとともに、悪夢は継続します!'	,
'Sell 1'	:	'1つ売る'	,
'<small>[owned : '	:	'<small>[所有 : '	,
'Cursor'	:	'カーソル'	,
'cursor|cursors|clicked'	:	'カーソル|カーソル|クリックされた'	,
'Autoclicks once every 10 seconds.'	:	'10秒に一度、自動クリックします。'	,
'Grandma'	:	'おばあちゃん'	,
'grandma|grandmas|baked'	:	'おばあちゃん|おばあちゃん|焼かれた'	,
'A nice grandma to bake more cookies.'	:	'たくさんクッキーを焼く素敵なおばあちゃん。'	,
'Farm'	:	'農場'	,
'farm|farms|harvested'	:	'農場|農場|収穫された'	,
'Grows cookie plants from cookie seeds.'	:	'クッキーの種からクッキー植物を育てます。'	,
'Factory'	:	'工場'	,
'factory|factories|mass-produced'	:	'工場|工場|大量生産された'	,
'Produces large quantities of cookies.'	:	'クッキーを大量生産します。'	,
'Mine'	:	'鉱山'	,
'mine|mines|mined'	:	'鉱山|鉱山|採掘した'	,
'Mines out cookie dough and chocolate chips.'	:	'鉱山はクッキー生地とチョコレートチップを採掘します。'	,
'Shipment'	:	'宇宙船'	,
'shipment|shipments|shipped'	:	'宇宙船|宇宙船|送られた'	,
'Brings in fresh cookies from the cookie planet.'	:	'クッキー惑星から新鮮なクッキーを持ち込みます。'	,
'Alchemy lab'	:	'錬金術研究所'	,
'alchemy lab|alchemy labs|transmuted'	:	'錬金術研究所|錬金術研究所|錬成された'	,
'Turns gold into cookies!'	:	'金をクッキーに変えます!'	,
'Portal'	:	'ポータル'	,
'portal|portals|retrieved'	:	'ポータル|ポータル|検索された'	,
'Opens a door to the Cookieverse.'	:	'クッキー宇宙への扉を開きます。'	,
'Time machine'	:	'タイムマシン'	,
'time machine|time machines|recovered'	:	'タイムマシン|タイムマシン|回復された'	,
'Brings cookies from the past, before they were even eaten.'	:	'クッキーが食べられる前の過去からクッキーをもたらします。'	,
'Antimatter condenser'	:	'反物質コンデンサー'	,
'antimatter condenser|antimatter condensers|condensed'	:	'反物質コンデンサー|反物質コンデンサー|圧縮された'	,
'Condenses the antimatter in the universe into cookies.'	:	'クッキーへ宇宙の反物質を圧縮します。'	,
'Reinforced index finger'	:	'強化された人差し指'	,
'The mouse gains <b>+1</b> cookie per click.<br>Cursors gain <b>+0.1</b> base CpS.<q>prod prod</q>'	:	'マウスは、1クリック当たり<b>+1</b>つのクッキーを獲得します。<br>カーソルは<b>+0.1</b>の基礎CpSを獲得します。<q>突き突き</q>'	,
'Carpal tunnel prevention cream'	:	'腱鞘炎予防クリーム'	,
'The mouse and cursors are <b>twice</b> as efficient.'	:	'マウスとカーソルの効率が<b>二倍</b>になります。'	,
'Ambidextrous'	:	'両手利き'	,
'The mouse and cursors are <b>twice</b> as efficient.<q>Look ma, both hands!</q>'	:	'マウスとカーソルの効率が<b>二倍</b>になります。<q>ma、両方の手を見てください!</q>'	,
'Thousand fingers'	:	'1000本の指'	,
'The mouse and cursors gain <b>+0.1</b> cookies for each non-cursor object owned.<q>clickity</q>'	:	'マウスとカーソルは、所有された各非カーソル・オブジェクトにつき<b>+0.1</b>のクッキーを獲得します。<q>clickity</q>'	,
'Million fingers'	:	'100万本の指'	,
'The mouse and cursors gain <b>+0.5</b> cookies for each non-cursor object owned.<q>clickityclickity</q>'	:	'マウスとカーソルは、所有された各非カーソル・オブジェクトにつき<b>+0.5</b>のクッキーを獲得します。<q>clickityclickity</q>'	,
'Billion fingers'	:	'10億本の指'	,
'The mouse and cursors gain <b>+2</b> cookies for each non-cursor object owned.<q>clickityclickityclickity</q>'	:	'マウスとカーソルは、所有された各非カーソル・オブジェクトにつき<b>+2</b>つのクッキーを獲得します。<q>clickityclickityclickity</q>'	,
'Trillion fingers'	:	'1兆本の指'	,
'The mouse and cursors gain <b>+10</b> cookies for each non-cursor object owned.<q>clickityclickityclickityclickity</q>'	:	'マウスとカーソルは、所有された各非カーソル・オブジェクトにつき<b>+10</b>のクッキーを獲得します。<q>clickityclickityclickityclickity</q>'	,
'Forwards from grandma'	:	'おばあちゃんからの順'	,
'Grandmas gain <b>+0.3</b> base CpS.<q>RE:RE:thought you\'d get a kick out of this ;))</q>'	:	'おばあちゃんは<b>+0.3</b>の基礎CpSを獲得します。<q>RE : RE : これで喜びを得るだろうと思いました;</q>'	,
'Steel-plated rolling pins'	:	'鋼をめっきした麺棒'	,
'Grandmas are <b>twice</b> as efficient.'	:	'おばあちゃんの効率が<b>二倍</b>になります。'	,
'Lubricated dentures'	:	'円滑になった義歯'	,
'Grandmas are <b>twice</b> as efficient.<q>Squish</q>'	:	'おばあちゃんの効率が<b>二倍</b>になります。<q>ぴしゃぴしゃいう音</q>'	,
'Cheap hoes'	:	'安いくわ'	,
'Farms gain <b>+0.5</b> base CpS.'	:	'農場は<b>+0.5</b>の基礎CpSを獲得します。'	,
'Fertilizer'	:	'肥料'	,
'Farms are <b>twice</b> as efficient.<q>It\'s chocolate, I swear.</q>'	:	'農場の効率が<b>二倍</b>になります。<q>それはチョコレートです。私は誓います。</q>'	,
'Cookie trees'	:	'クッキー木'	,
'Farms are <b>twice</b> as efficient.<q>A relative of the breadfruit.</q>'	:	'農場の効率が<b>二倍</b>になります。<q>パンの木の実の関係詞。</q>'	,
'Sturdier conveyor belts'	:	'より頑丈なコンベヤーベルト'	,
'Factories gain <b>+4</b> base CpS.'	:	'工場は<b>+4</b>の基礎CpSを獲得します。'	,
'Child labor'	:	'幼年労働'	,
'Factories are <b>twice</b> as efficient.<q>Cheaper, healthier workforce - and so much more receptive to whipping!</q>'	:	'工場の効率が<b>二倍</b>になります。<q>より安く、より健康な労働力 - そして、鞭打ちに非常にはるかに、もっと受容力があります!</q>'	,
'Sweatshop'	:	'スエットショップ'	,
'Factories are <b>twice</b> as efficient.<q>Slackers will be terminated.</q>'	:	'工場の効率が<b>二倍</b>になります。<q>怠け者は終了するでしょう。</q>'	,
'Sugar gas'	:	'砂糖ガス'	,
'Mines gain <b>+10</b> base CpS.<q>A pink, volatile gas, found in the depths of some chocolate caves.</q>'	:	'鉱山は<b>+10</b>の基礎CpSを獲得します。<q>いくつかのチョコレート洞穴の真中で見つかったピンク、揮発性のガス。</q>'	,
'Megadrill'	:	'メガドリル'	,
'Mines are <b>twice</b> as efficient.'	:	'鉱山の効率が<b>二倍</b>になります。'	,
'Ultradrill'	:	'Ultradrill'	,
'Vanilla nebulae'	:	'バニラ星雲'	,
'Shipments gain <b>+30</b> base CpS.'	:	'宇宙船は<b>+30</b>の基礎CpSを獲得します。'	,
'Wormholes'	:	'虫の掘った穴'	,
'Shipments are <b>twice</b> as efficient.<q>By using these as shortcuts, your ships can travel much faster.</q>'	:	'宇宙船の効率が<b>二倍</b>になります。<q>ショートカットとしてこれらを使用することで、船ははるかに速く移動することができます。</q>'	,
'Frequent flyer'	:	'頻繁なフライヤ'	,
'Shipments are <b>twice</b> as efficient.<q>Come back soon!</q>'	:	'宇宙船の効率が<b>二倍</b>になります。<q>すぐに戻ってきてください!</q>'	,
'Antimony'	:	'アンチモニー'	,
'Alchemy labs gain <b>+100</b> base CpS.<q>Actually worth a lot of mony.</q>'	:	'錬金術研究所は<b>+100</b>の基礎CpSを獲得します。<q>多くのmonyの価値で実際に。</q>'	,
'Essence of dough'	:	'生地の本質'	,
'Alchemy labs are <b>twice</b> as efficient.<q>Extracted through the 5 ancient steps of alchemical baking.</q>'	:	'錬金術研究所の効率が<b>二倍</b>になります。<q>古代の5ステップの錬金術のから焼きによって抽出されました。</q>'	,
'True chocolate'	:	'真実のチョコレート'	,
'Alchemy labs are <b>twice</b> as efficient.<q>The purest form of cacao.</q>'	:	'錬金術研究所の効率が<b>二倍</b>になります。<q>カカオの最も純粋な形式。</q>'	,
'Ancient tablet'	:	'古代のタブレット'	,
'Portals gain <b>+1,666</b> base CpS.<q>A strange slab of peanut brittle, holding an ancient cookie recipe. Neat!</q>'	:	'ポータルは<b>+1,666</b>の基礎CpSを獲得します。<q>古代のクッキーのレシピを保持して、ピーナッツの奇妙なスラブは脆い。きれいです!</q>'	,
'Insane oatling workers'	:	'狂気のoatlingする労働者'	,
'Portals are <b>twice</b> as efficient.<q>ARISE, MY MINIONS!</q>'	:	'ポータルの効率が<b>二倍</b>になります。<q>発生する、私の手先!</q>'	,
'Soul bond'	:	'魂ボンド'	,
'Portals are <b>twice</b> as efficient.<q>So I just sign up and get more cookies? Sure, whatever!</q>'	:	'ポータルの効率が<b>二倍</b>になります。<q>したがって、私はちょうど参加し、より多くのクッキーを得ます?確かに、何でも!</q>'	,
'Flux capacitors'	:	'フラックス・コンデンサー'	,
'Time machines gain <b>+9,876</b> base CpS.<q>Bake to the future.</q>'	:	'タイムマシンは<b>+9,876</b>の基礎CpSを獲得します。<q>将来に焼けてください。</q>'	,
'Time paradox resolver'	:	'時間逆説リゾルバ'	,
'Time machines are <b>twice</b> as efficient.<q>No more fooling around with your own grandmother!</q>'	:	'タイムマシンの効率が<b>二倍</b>になります。<q>自分の祖母ともうふざけないこと!</q>'	,
'Quantum conundrum'	:	'クオンタムのなぞ'	,
'Time machines are <b>twice</b> as efficient.<q>It\'s full of stars!</q>'	:	'タイムマシンの効率が<b>二倍</b>になります。<q>それは星でいっぱいです!</q>'	,
'Kitten helpers'	:	'子ネコ助手'	,
'You gain <b>more CpS</b> the more milk you have.<q>meow may I help you</q>'	:	'より多くのミルクを飲むほど、より<b>多くのCpS</b>を獲得します。<q>にゃーお、だろう、私はあなたを助けます。</q>'	,
'Kitten workers'	:	'子ネコ労働者'	,
'You gain <b>more CpS</b> the more milk you have.<q>meow meow meow meow</q>'	:	'より多くのミルクを飲むほど、より<b>多くのCpS</b>を獲得します。<q>にゃーおにゃーおにゃーおにゃーお</q>'	,
'Oatmeal raisin cookies'	:	'オートミール・レーズン・クッキー'	,
'Cookie production multiplier <b>+5%</b>.<q>No raisin to hate these.</q>'	:	'クッキー生産乗数<b>5+%</b>。<q>これらを嫌うレーズンはない。</q>'	,
'Peanut butter cookies'	:	'ピーナッツバター・クッキー'	,
'Cookie production multiplier <b>+5%</b>.'	:	'クッキー生産乗数<b>5+%</b>。'	,
'Plain cookies'	:	'平易なクッキー'	,
'Cookie production multiplier <b>+5%</b>.<q>Meh.</q>'	:	'クッキー生産乗数<b>5+%</b>。<q>Meh。</q>'	,
'Coconut cookies'	:	'ココナッツ・クッキー'	,
'White chocolate cookies'	:	'ホワイトチョコレート・クッキー'	,
'Macadamia nut cookies'	:	'マカダミアナッツ・クッキー'	,
'Double-chip cookies'	:	'2倍のチップのクッキー'	,
'Cookie production multiplier <b>+10%</b>.'	:	'クッキー生産乗数<b>10+%</b>。'	,
'Sugar cookies'	:	'砂糖クッキー'	,
'White chocolate macadamia nut cookies'	:	'ホワイトチョコレート・マカダミアナッツ・クッキー'	,
'All-chocolate cookies'	:	'全チョコレート菓子'	,
'Quadrillion fingers'	:	'1000兆本の指'	,
'The mouse and cursors gain <b>+20</b> cookies for each non-cursor object owned.<q>clickityclickityclickityclickityclick</q>'	:	'マウスとカーソルは、所有された各非カーソル・オブジェクトにつき<b>+20</b>のクッキーを獲得します。<q>clickityclickityclickityclickityclick</q>'	,
'Prune juice'	:	'プルーン・ジュース'	,
'Grandmas are <b>twice</b> as efficient.<q>Gets me going.</q>'	:	'おばあちゃんの効率が<b>二倍</b>になります。<q>私を行かせます。</q>'	,
'Genetically-modified cookies'	:	'遺伝子組み換えのクッキー'	,
'Farms are <b>twice</b> as efficient.<q>All-natural mutations.</q>'	:	'農場の効率が<b>二倍</b>になります。<q>全く自然な変化。</q>'	,
'Radium reactors'	:	'ラジウム・リアクター'	,
'Factories are <b>twice</b> as efficient.<q>Gives your cookies a healthy glow.</q>'	:	'工場の効率が<b>二倍</b>になります。<q>クッキーに健全なグローを与えます。</q>'	,
'Ultimadrill'	:	'Ultimadrill'	,
'Mines are <b>twice</b> as efficient.<q>Pierce the heavens, etc.</q>'	:	'鉱山の効率が<b>二倍</b>になります。<q>天などを貫通します。</q>'	,
'Warp drive'	:	'Warpドライブ'	,
'Shipments are <b>twice</b> as efficient.'	:	'宇宙船の効率が<b>二倍</b>になります。'	,
'Ambrosia'	:	'アンブローシア'	,
'Alchemy labs are <b>twice</b> as efficient.'	:	'錬金術研究所の効率が<b>二倍</b>になります。'	,
'Sanity dance'	:	'正気ダンス'	,
'Portals are <b>twice</b> as efficient.<q>We can change if we want to.<br>We can leave our brains behind.</q>'	:	'ポータルの効率が<b>二倍</b>になります。<q>私たちは、そうしたければ、変わることができます。<br>私たちは脳を後に残すことができます。</q>'	,
'Causality enforcer'	:	'因果律エンフォーサー'	,
'Time machines are <b>twice</b> as efficient.<q>What happened, happened.</q>'	:	'タイムマシンの効率が<b>二倍</b>になります。<q>起こったことが起こりました。</q>'	,
'Lucky day'	:	'幸運な日'	,
'Golden cookies appear <b>twice as often</b> and last <b>twice as long</b>.'	:	'金のクッキーが現われます、<b>二倍、として、しばしば</b>、そして<b>二倍最後、として、長い</b>'	,
'Serendipity'	:	'セレンディピティ'	,
'Kitten engineers'	:	'子ネコエンジニア'	,
'You gain <b>more CpS</b> the more milk you have.<q>meow meow meow meow, sir</q>'	:	'より多くのミルクを飲むほど、より<b>多くのCpS</b>を獲得します。<q>にゃーおにゃーおにゃーおにゃーお、貴下</q>'	,
'Dark chocolate-coated cookies'	:	'ダーク・チョコレートを上塗りを施したクッキー'	,
'Cookie production multiplier <b>+15%</b>.'	:	'クッキー生産乗数<b>15+%</b>。'	,
'White chocolate-coated cookies'	:	'ホワイトチョコレートを上塗りを施したクッキー'	,
'Farmer grandmas'	:	'ファーマーのおばあちゃん'	,
'Worker grandmas'	:	'労働者おばあちゃん'	,
'Miner grandmas'	:	'鉱夫おばあちゃん'	,
'Cosmic grandmas'	:	'宇宙のおばあちゃん'	,
'Transmuted grandmas'	:	'錬成されたおばあちゃん'	,
'Altered grandmas'	:	'変更されたおばあちゃん'	,
'Grandmas\' grandmas'	:	'おばあちゃんのおばあちゃん'	,
'Research has begun.'	:	'研究は始まりました。'	,
'Bingo center/Research facility'	:	'ビンゴ・センター/研究設備'	,
'Grandma-operated science lab and leisure club.<br>Grandmas are <b>4 times</b> as efficient.<br><b>Regularly unlocks new upgrades</b>.'	:	'おばあちゃん作動科学研究所とレジャー・クラブ。<br>おばあちゃんは<b>4倍</b>同じくらい効率的です。<br><b>規則的に、新しいアップグレードを開けます</b>。'	,
'Specialized chocolate chips'	:	'専門のチョコレートチップ'	,
'[Research]<br>Cookie production multiplier <b>+1%</b>.<q>Computer-designed chocolate chips. Computer chips, if you will.</q>'	:	'[研究]<br>クッキー生産乗数<b>1+%</b>。<q>コンピューターが設計したチョコレートチップ。あなたがすれば、コンピューターは削ります。</q>'	,
'Designer cocoa beans'	:	'デザイナー・カカオ豆'	,
'[Research]<br>Cookie production multiplier <b>+2%</b>.<q>Now more aerodynamic than ever!</q>'	:	'[研究]<br>クッキー生産乗数<b>2+%</b>。<q>今これまでより航空力学です!</q>'	,
'Ritual rolling pins'	:	'儀式の麺棒'	,
'[Research]<br>Grandmas are <b>twice</b> as efficient.<q>The result of years of scientific research!</q>'	:	'[研究]<br>おばあちゃんの効率が<b>二倍</b>になります。<q>数年間の科学的調査の結果!</q>'	,
'Underworld ovens'	:	'暗黒街オーブン'	,
'[Research]<br>Cookie production multiplier <b>+3%</b>.<q>Powered by science, of course!</q>'	:	'[研究]<br>クッキー生産乗数<b>3+%</b>。<q>もちろん科学で動力が供給されました!</q>'	,
'One mind'	:	'1つの心'	,
'[Research]<br>Each grandma gains <b>+1 base CpS for each 50 grandmas</b>.<div class="warning">Note : the grandmothers are growing restless. Do not encourage them.</div><q>We are one. We are many.</q>'	:	'[研究]<br>おばあちゃんはそれぞれ、<b>各50人のおばあちゃんにつき+1の基礎CpS</b>を獲得します。<div class="warning">注 : 祖母は落ち着かなくなっています。それらを促進しないでください。</div><q>私たちは1です。私たちは多い。</q>'	,
'Exotic nuts'	:	'新種のナット'	,
'[Research]<br>Cookie production multiplier <b>+4%</b>.<q>You\'ll go crazy over these!</q>'	:	'[研究]<br>クッキー生産乗数<b>4+%</b>。<q>これらに夢中になるでしょう!</q>'	,
'Communal brainsweep'	:	'公共のbrainsweep'	,
'[Research]<br>Each grandma gains another <b>+1 base CpS for each 50 grandmas</b>.<div class="warning">Note : proceeding any further in scientific research may have unexpected results. You have been warned.</div><q>We fuse. We merge. We grow.</q>'	:	'[研究]<br>おばあちゃんはそれぞれ別の<b>+を獲得します、各50人のおばあちゃんにつき1の基礎CpS</b>。<div class="warning">注 : 科学的調査の中でそれ以上進むことは予期しない結果を持っているかもしれません。警告されました。</div><q>私たちは融合します。私たちは合併します。私たちは成長します。</q>'	,
'Arcane sugar'	:	'不可解な砂糖'	,
'[Research]<br>Cookie production multiplier <b>+5%</b>.<q>Tastes like insects, ligaments, and molasses.</q>'	:	'[研究]<br>クッキー生産乗数<b>5+%</b>。<q>昆虫、リガメントと糖蜜のような味がします。</q>'	,
'Elder Pact'	:	'年上協定'	,
'[Research]<br>Each grandma gains <b>+1 base CpS for each 20 portals</b>.<div class="warning">Note : this is a bad idea.</div><q>squirm crawl slither writhe<br>today we rise</q>'	:	'[研究]<br>おばあちゃんはそれぞれ、<b>各20のポータルにつき+1の基礎CpS</b>を獲得します。<div class="warning">注 : これは悪い考えです。</div><q>体をねじる、徐行滑走苦悶 <br>今日、私たちは起きます。</q>'	,
'Elder Pledge'	:	'年上誓約'	,
'[Repeatable]<br>Contains the wrath of the elders, at least for a while.'	:	'[反復可能で]<br>少なくともしばらくの間年長者の激怒を含んでいます。'	,
'Plastic mouse'	:	'プラスチック・マウス'	,
'Clicking gains <b>+1% of your CpS</b>.'	:	'クリックは、<b>CpSの+1%</b>を獲得します。'	,
'Iron mouse'	:	'鉄のマウス'	,
'Titanium mouse'	:	'チタンのマウス'	,
'Adamantium mouse'	:	'アダマンティウムのマウス'	,
'Ultrascience'	:	'超科学'	,
'Research takes only <b>5 seconds</b>.'	:	'研究はわずか<b>5秒</b>しかかかりません。'	,
'Eclipse cookies'	:	'クッキーの影を薄くします。'	,
'Cookie production multiplier <b>+15%</b>.<q>Look to the cookie.</q>'	:	'クッキー生産乗数<b>15+%</b>。<q>クッキーに目を向けてください。</q>'	,
'Zebra cookies'	:	'シマウマ・クッキー'	,
'Quintillion fingers'	:	'Quintillion指'	,
'The mouse and cursors gain <b>+100</b> cookies for each non-cursor object owned.<q>man, just go click click click click click, it\'s real easy, man.</q>'	:	'マウスとカーソルは、所有された各非カーソル・オブジェクトにつき<b>+100</b>のクッキーを獲得します。<q>人、単に進行、クリック・クリック・クリック・クリック・クリック、それはまったく容易です、man. </q>'	,
'Gold hoard'	:	'金蓄え'	,
'Golden cookies appear <b>really often</b>.'	:	'金のクッキーが<b>実際にしばしば</b>現われます。'	,
'Elder Covenant'	:	'年上契約'	,
'[Switch]<br>Puts a permanent end to the elders\' wrath, at the price of 5% of your CpS.'	:	'[スイッチ]<br>CpSの5%を犠牲にして、年長者の激怒の永久の終わりを置きます。'	,
'Revoke Elder Covenant'	:	'廃止の年上契約'	,
'[Switch]<br>You will get 5% of your CpS back, but the grandmatriarchs will return.'	:	'[スイッチ]<br>あなたは、CpSの5%を戻すでしょう。しかし、おばあちゃんtriarchsは返るでしょう。'	,
'Get lucky'	:	'幸運になります。'	,
'Golden cookie effects last <b>twice as long</b>.<q>You\'ve been up all night, haven\'t you?</q>'	:	'<b>二倍同じように長く</b>最後の金のクッキー結果。<q>一晩中起きていますね。</q>'	,
'Sacrificial rolling pins'	:	'犠牲の麺棒'	,
'Elder pledge last <b>twice</b> as long.'	:	'<b>二倍</b>同じように長く最後の年上の誓約。'	,
'Snickerdoodles'	:	'Snickerdoodles'	,
'Stroopwafels'	:	'Stroopwafels'	,
'Cookie production multiplier <b>+15%</b>.<q>If it ain\'t dutch, it ain\'t much.</q>'	:	'クッキー生産乗数<b>15+%</b>。<q>それは、それが女房でない場合、多くではありません。</q>'	,
'Macaroons'	:	'マカロン'	,
'Neuromancy'	:	'Neuromancy'	,
'Can toggle upgrades on and off at will in the stats menu.'	:	'時々アップグレードをトグルで留めることができる、で、統計メニューの中でするでしょう。'	,
'Empire biscuits'	:	'帝国ビスケット'	,
'British tea biscuits'	:	'英国ティービスケット'	,
'Chocolate british tea biscuits'	:	'チョコレート英国ティービスケット'	,
'Round british tea biscuits'	:	'円形の英国ティービスケット'	,
'Round chocolate british tea biscuits'	:	'円形のチョコレート英国ティービスケット'	,
'Round british tea biscuits with heart motif'	:	'心臓モチーフを備えた円形の英国ティービスケット'	,
'Round chocolate british tea biscuits with heart motif'	:	'心臓モチーフを備えた円形のチョコレート英国ティービスケット'	,
'Cookie production multiplier <b>+15%</b>.<q>Quite.</q>'	:	'クッキー生産乗数<b>15+%</b>。<q>。(全く)</q>'	,
'Sugar bosons'	:	'砂糖ボゾン'	,
'Antimatter condensers gain <b>+99,999</b> base CpS.'	:	'反物質コンデンサーは<b>+99,999</b>の基礎CpSを獲得します。'	,
'String theory'	:	'超ひも理論'	,
'Antimatter condensers are <b>twice</b> as efficient.'	:	'反物質コンデンサーの効率が<b>二倍</b>になります。'	,
'Large macaron collider'	:	'大きなmacaronコライダー'	,
'Antimatter condensers are <b>twice</b> as efficient.<q>How singular!</q>'	:	'反物質コンデンサーの効率が<b>二倍</b>になります。<q>何て珍しいのでしょう!</q>'	,
'Big bang bake'	:	'ビッグバン、焼ける。'	,
'Antimatter condensers are <b>twice</b> as efficient.<q>And that\'s how it all began.</q>'	:	'反物質コンデンサーの効率が<b>二倍</b>になります。<q>また、このようにして、それはすべて始まりました。</q>'	,
'Antigrandmas'	:	'反おばあちゃん'	,
'Madeleines'	:	'マドレーヌ'	,
'Cookie production multiplier <b>+20%</b>.<q>Unforgettable!</q>'	:	'クッキー生産乗数<b>20+%</b>。<q>忘れがたい!</q>'	,
'Palmiers'	:	'パルミエ'	,
'Cookie production multiplier <b>+20%</b>.'	:	'クッキー生産乗数<b>20+%</b>。'	,
'Palets'	:	'パレ'	,
'Sabl&eacute;s'	:	'Sabl &eacute; s'	,
'Kitten overseers'	:	'子ネコ監督者'	,
'You gain <b>more CpS</b> the more milk you have.<q>my purrpose is to serve you, sir</q>'	:	'より多くのミルクを飲むほど、より<b>多くのCpS</b>を獲得します。<q>私のpurrposeはあなたと貴下のために役立つ予定です。</q>'	,
'Plain milk'	:	'平易なミルク'	,
'Unlocks <b>plain milk</b>, available in the menu.'	:	'<b>平易なミルク</b>(メニューにおいて利用可能)を開けます。'	,
'Chocolate milk'	:	'チョコレートミルク'	,
'Unlocks <b>chocolate milk</b>, available in the menu.'	:	'<b>チョコレートミルク</b>(メニューにおいて利用可能)を開けます。'	,
'Raspberry milk'	:	'ラズベリー・ミルク'	,
'Unlocks <b>raspberry milk</b>, available in the menu.'	:	'<b>ラズベリー・ミルク</b>(メニューにおいて利用可能)を開けます。'	,
'Ain\'t got milk'	:	'ミルクを得られません。'	,
'Unlocks <b>no milk please</b>, available in the menu.'	:	'<b>ミルクを開けない、どうぞ</b>、メニューにおいて利用可能。'	,
'Blue background'	:	'青い背景'	,
'Unlocks the <b>blue background</b>, available in the menu.'	:	'<b>青い背景</b>(メニューにおいて利用可能)を開けます。'	,
'Red background'	:	'赤い背景'	,
'Unlocks the <b>red background</b>, available in the menu.'	:	'<b>赤い背景</b>(メニューにおいて利用可能)を開けます。'	,
'White background'	:	'白い背景'	,
'Unlocks the <b>white background</b>, available in the menu.'	:	'<b>白い背景</b>(メニューにおいて利用可能)を開けます。'	,
'Black background'	:	'黒背景'	,
'Unlocks the <b>black background</b>, available in the menu.'	:	'<b>黒背景</b>(メニューにおいて利用可能)を開けます。'	,
'Achievement unlocked :<br>'	:	'実績をアンロックしました : <br>'	,
'name'	:	'名前'	,
'description'	:	'説明'	,
'Wake and bake'	:	'起きて焼けます。'	,
'Making some dough'	:	'いくらかの生地を作ること'	,
'So baked right now'	:	'したがって、今ちょうど焼かれた。'	,
'Fledgling bakery'	:	'駆け出しのベーカリー'	,
'Affluent bakery'	:	'豊富なベーカリー'	,
'World-famous bakery'	:	'世界的に有名なベーカリー'	,
'Cosmic bakery'	:	'宇宙のベーカリー'	,
'Galactic bakery'	:	'銀河のベーカリー'	,
'Universal bakery'	:	'ユニバーサルなベーカリー'	,
'Timeless bakery'	:	'永遠のベーカリー'	,
'Infinite bakery'	:	'無限のベーカリー'	,
'Immortal bakery'	:	'永久のベーカリー'	,
'You can stop now'	:	'今停止することができます。'	,
'Cookies all the way down'	:	'クッキーは途中ずっとダウンしています。'	,
'Overdose'	:	'過剰服用'	,
'How?'	:	'どのように?'	,
'Bake <b>{0}</b> cookie{1}.'	:	'<b>{0}</b>クッキー{1}を焼いてください。'	,
'Casual baking'	:	'偶然のから焼き'	,
'Hardcore baking'	:	'ハードコア・パン焼き'	,
'Steady tasty stream'	:	'絶え間ない味のよいストリーム'	,
'Cookie monster'	:	'クッキー怪物'	,
'Mass producer'	:	'多量発生炉'	,
'Cookie vortex'	:	'クッキー渦'	,
'Cookie pulsar'	:	'クッキー・パルサー'	,
'Cookie quasar'	:	'クッキー・クエーサー'	,
'A world filled with cookies'	:	'世界はクッキーで満たされました。'	,
'Let\'s never bake again'	:	'再び焼けないでおきましょう。'	,
'Bake <b>{0}</b> cookie{1} per second.'	:	'毎秒<b>{0}</b>クッキー{1}を焼いてください。'	,
'Sacrifice'	:	'犠牲'	,
'Reset your game with <b>1 million</b> cookies baked.<q>Easy come, easy go.</q>'	:	'<b>100万</b>のクッキーを焼いて、ゲームをリセットしてください。<q>悪銭身につかず。</q>'	,
'Oblivion'	:	'忘却'	,
'Reset your game with <b>1 billion</b> cookies baked.<q>Back to square one.</q>'	:	'<b>10億</b>のクッキーを焼いて、ゲームをリセットしてください。<q>出発点に。</q>'	,
'From scratch'	:	'ゼロから'	,
'Reset your game with <b>1 trillion</b> cookies baked.<q>It\'s been fun.</q>'	:	'<b>1兆</b>のクッキーを焼いて、ゲームをリセットしてください。<q>それは楽しかった。</q>'	,
'Neverclick'	:	'Neverclick'	,
'Make <b>1 million</b> cookies by only having clicked <b>15 times</b>.'	:	'<b>15回</b>単にクリックしたことにより<b>100万</b>のクッキーを作ってください。'	,
'Clicktastic'	:	'Clicktastic'	,
'Make <b>1,000</b> cookies from clicking.'	:	'クリックで<b>1,000</b>のクッキーを作ってください。'	,
'Clickathlon'	:	'Clickathlon'	,
'Make <b>100,000</b> cookies from clicking.'	:	'クリックで<b>100,000</b>のクッキーを作ってください。'	,
'Clickolympics'	:	'Clickolympics'	,
'Make <b>10,000,000</b> cookies from clicking.'	:	'クリックで<b>10,000,000</b>のクッキーを作ってください。'	,
'Clickorama'	:	'Clickorama'	,
'Make <b>1,000,000,000</b> cookies from clicking.'	:	'クリックで<b>1,000,000,000</b>のクッキーを作ってください。'	,
'Click'	:	'クリック'	,
'Have <b>1</b> cursor.'	:	'<b>1</b>つのカーソルを持っています。'	,
'Double-click'	:	'ダブルクリック'	,
'Have <b>2</b> cursors.'	:	'<b>2</b>つのカーソルを持っています。'	,
'Mouse wheel'	:	'マウスホイール'	,
'Have <b>50</b> cursors.'	:	'<b>50</b>のカーソルを持っています。'	,
'Of Mice and Men'	:	'マウスと人間'	,
'Have <b>100</b> cursors.'	:	'<b>100</b>のカーソルを持っています。'	,
'The Digital'	:	'ディジタル'	,
'Have <b>200</b> cursors.'	:	'<b>200</b>のカーソルを持っています。'	,
'Just wrong'	:	'ちょうど間違っています。'	,
'Sell a grandma.<q>I thought you loved me.</q>'	:	'おばあちゃんを売ってください。<q>私は、あなたは私を愛すると思いました。</q>'	,
'Grandma\'s cookies'	:	'おばあちゃんのクッキー'	,
'Have <b>1</b> grandma.'	:	'<b>1</b>人のおばあちゃんを持っています。'	,
'Sloppy kisses'	:	'水だらけのキス'	,
'Have <b>50</b> grandmas.'	:	'<b>50</b>人のおばあちゃんを持っています。'	,
'Retirement home'	:	'退職者向けホーム'	,
'Have <b>100</b> grandmas.'	:	'<b>100</b>人のおばあちゃんを持っています。'	,
'My first farm'	:	'私の最初の農場'	,
'Have <b>1</b> farm.'	:	'<b>1</b>つの農場を持っています。'	,
'Reap what you sow'	:	'あなたがまくものを収穫します。'	,
'Have <b>50</b> farms.'	:	'<b>50</b>の農場を持っています。'	,
'Farm ill'	:	'悪くて農業をします。'	,
'Have <b>100</b> farms.'	:	'<b>100</b>の農場を持っています。'	,
'Production chain'	:	'生産鎖'	,
'Have <b>1</b> factory.'	:	'<b>1</b>つの工場を持っています。'	,
'Industrial revolution'	:	'産業革命'	,
'Have <b>50</b> factories.'	:	'<b>50</b>の工場を持っています。'	,
'Global warming'	:	'地球温暖化'	,
'Have <b>100</b> factories.'	:	'<b>100</b>の工場を持っています。'	,
'You know the drill'	:	'ドリルを知っています。'	,
'Have <b>1</b> mine.'	:	'<b>1</b>つの鉱山を持っています。'	,
'Excavation site'	:	'発掘サイト'	,
'Have <b>50</b> mines.'	:	'<b>50</b>の鉱山を持っています。'	,
'Hollow the planet'	:	'惑星をくぼめます。'	,
'Have <b>100</b> mines.'	:	'<b>100</b>の鉱山を持っています。'	,
'Expedition'	:	'滞在'	,
'Have <b>1</b> shipment.'	:	'<b>1</b>つの宇宙船をしてください。'	,
'Galactic highway'	:	'銀河のハイウェイ'	,
'Have <b>50</b> shipments.'	:	'<b>50</b>の宇宙船をしてください。'	,
'Far far away'	:	'ずっと遠くに遠い。'	,
'Have <b>100</b> shipments.'	:	'<b>100</b>の宇宙船をしてください。'	,
'Transmutation'	:	'変換'	,
'Have <b>1</b> alchemy lab.'	:	'<b>1</b>つの錬金術研究所を持っています。'	,
'Transmogrification'	:	'錬成'	,
'Have <b>50</b> alchemy labs.'	:	'<b>50</b>の錬金術研究所を持っています。'	,
'Gold member'	:	'金のメンバー'	,
'Have <b>100</b> alchemy labs.'	:	'<b>100</b>の錬金術研究所を持っています。'	,
'A whole new world'	:	'全く新しい世界'	,
'Have <b>1</b> portal.'	:	'<b>1</b>つのポータルを持っています。'	,
'Now you\'re thinking'	:	'今、考えています。'	,
'Have <b>50</b> portals.'	:	'<b>50</b>のポータルを持っています。'	,
'Dimensional shift'	:	'次元の変更'	,
'Have <b>100</b> portals.'	:	'<b>100</b>のポータルを持っています。'	,
'Time warp'	:	'タイムワープ'	,
'Have <b>1</b> time machine.'	:	'<b>1</b>つのタイムマシンを持っています。'	,
'Alternate timeline'	:	'交互のスケジュール'	,
'Have <b>50</b> time machines.'	:	'<b>50</b>のタイムマシンを持っています。'	,
'Rewriting history'	:	'歴史の改変'	,
'Have <b>100</b> time machines.'	:	'<b>100</b>のタイムマシンを持っています。'	,
'One with everything'	:	'すべてを備えた一つ'	,
'Have <b>at least 1</b> of every building.'	:	'<b>少なくともすべての建物の1</b>を持っています。'	,
'Mathematician'	:	'数学者'	,
'Have at least <b>1 time machine, 2 portals, 4 alchemy labs, 8 shipments</b> and so on (128 max).'	:	'少なくとも<b>1つのタイムマシン、2つのポータル、4つの錬金術研究所、8つの宇宙船</b>など(128の最大)を持っています。'	,
'Base 10'	:	'基礎10'	,
'Have at least <b>10 time machines, 20 portals, 30 alchemy labs, 40 shipments</b> and so on.'	:	'少なくとも<b>10のタイムマシン、20のポータル、30の錬金術研究所、40の宇宙船</b>などを持っています。'	,
'Golden cookie'	:	'金のクッキー'	,
'Click a <b>golden cookie</b>.'	:	'<b>金のクッキー</b>をクリックしてください。'	,
'Lucky cookie'	:	'幸運なクッキー'	,
'Click <b>7 golden cookies</b>.'	:	'<b>7つの金のクッキー</b>をクリックしてください。'	,
'A stroke of luck'	:	'思いがけない幸運'	,
'Click <b>27 golden cookies</b>.'	:	'<b>27の金のクッキー</b>をクリックしてください。'	,
'Cheated cookies taste awful'	:	'欺かれたクッキーは恐ろしい味がします。'	,
'Hack in some cookies.'	:	'いくつかのクッキー中で叩き切ってください。'	,
'Uncanny clicker'	:	'異様なリモコン'	,
'Click really, really fast.<q>Well I\'ll be!</q>'	:	'実際に実際に速くクリックしてください。<q>よく、私はそうだろう!</q>'	,
'Builder'	:	'ビルダー'	,
'Own <b>100</b> buildings.'	:	'<b>100</b>の建物を所有してください。'	,
'Architect'	:	'建築家'	,
'Own <b>400</b> buildings.'	:	'<b>400</b>の建物を所有してください。'	,
'Enhancer'	:	'エンハンサー'	,
'Purchase <b>20</b> upgrades.'	:	'購入<b>20</b>アップグレード。'	,
'Augmenter'	:	'拡大者'	,
'Purchase <b>50</b> upgrades.'	:	'購入<b>50</b>アップグレード。'	,
'Cookie-dunker'	:	'クッキー-dunker'	,
'Dunk the cookie.<q>You did it!</q>'	:	'クッキーを浸してください。<q>それをしました!</q>'	,
'Fortune'	:	'フォーチュン'	,
'Click <b>77 golden cookies</b>.<q>You should really go to bed.</q>'	:	'<b>77の金のクッキー</b>をクリックしてください。<q>実際に寝るべきです。</q>'	,
'True Neverclick'	:	'真実のNeverclick'	,
'Make <b>1 million</b> cookies with <b>no</b> cookie clicks.<q>This kinda defeats the whole purpose, doesn\'t it?</q>'	:	'クッキー・クリックなしで<b>100万</b>のクッキーを作ってください。<b></b><q>これはまあ目的全体をくじきますね。</q>'	,
'Elder nap'	:	'年上のうたた寝'	,
'Appease the grandmatriarchs at least <b>once</b>.<q>we<br>are<br>eternal</q>'	:	'おばあちゃんtriarchsを少なくとも<b>一度</b>和らげてください。<q>私たち<br>です。<br>永遠</q>'	,
'Elder slumber'	:	'年長者仮眠'	,
'Appease the grandmatriarchs at least <b>5 times</b>.<q>our mind<br>outlives<br>the universe</q>'	:	'おばあちゃんtriarchsを少なくとも<b>5回</b>和らげてください。<q>私たちの心<br>長く続きます。<br>宇宙</q>'	,
'Elder'	:	'年長者'	,
'Own every grandma type.'	:	'すべてのおばあちゃんタイプを所有してください。'	,
'Elder calm'	:	'年長者は静かです。'	,
'Declare a covenant with the grandmatriarchs.<q>we<br>have<br>fed</q>'	:	'おばあちゃんtriarchsを備えた契約を宣言してください。<q>私たち<br>持っています。<br>供給されました。</q>'	,
'Engineer'	:	'エンジニア'	,
'Own <b>800</b> buildings.'	:	'<b>800</b>の建物を所有してください。'	,
'Leprechaun'	:	'レプレコン'	,
'Click <b>777 golden cookies</b>.'	:	'<b>777の金のクッキー</b>をクリックしてください。'	,
'Black cat\'s paw'	:	'黒い猫の足'	,
'Click <b>7777 golden cookies</b>.'	:	'<b>7777の金のクッキー</b>をクリックしてください。'	,
'Nihilism'	:	'ニヒリズム'	,
'Reset your game with <b>1 quadrillion</b> cookies baked.<q>There are many things<br>that need to be erased</q>'	:	'<b>1000兆</b>のクッキーを焼いて、ゲームをリセットしてください。<q>多くのものがあります。<br>消されるその必要</q>'	,
'Galactus\' Reprimand'	:	'Galactusの懲戒'	,
'Reset your game with <b>1 quintillion</b> coo- okay no I'	:	'<b>1つのquintillion</b>クークーを備えたゲームをリセットする-承認する、ない、私 '	,
'Antibatter'	:	'反バッター'	,
'Have <b>1</b> antimatter condenser.'	:	'<b>1</b>つの反物質コンデンサーを持っています。'	,
'Quirky quarks'	:	'一種独特なクォーク'	,
'Have <b>50</b> antimatter condensers.'	:	'<b>50</b>の反物質コンデンサーを持っています。'	,
'It does matter!'	:	'それは重要です!'	,
'Have <b>100</b> antimatter condensers.'	:	'<b>100</b>の反物質コンデンサーを持っています。'	,
'Upgrader'	:	'Upgrader'	,
'Purchase <b>100</b> upgrades.'	:	'購入<b>100</b>アップグレード。'	,
'Centennial'	:	'百年'	,
'Have at least <b>100 of everything</b>.'	:	'少なくとも<b>すべての100</b>を持っています。'	,
'Researched : '	:	'研究されました : '	,
'You have unlocked the factory dungeons!'	:	'工場ダンジョンを開けました!'	,
' cookie'	:	' クッキー'	,
' cookies'	:	' クッキー'	,
'<br>cookies'	:	'<br>クッキー'	,
'<div style="font-size:50%;">per second : '	:	'<div style="font-size:50%;">毎秒 : '	,
'&bull; {0} {1}<br>&bull; producing {2} {3} per second<br>&bull; total : {4} {5} {6}'	:	'&bull; {0} {1}<br>&bull; 生産 {2} {3} 毎秒<br>&bull; 累計 : {4} {5}が{6}'	,
'cookie'	:	'クッキー'	,
'cookies'	:	'クッキー'	
};			